import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/free-mode";
import "swiper/css/thumbs";
import "./globals.css";
import Navbar from "@/components/layout/Navbar/Navbar";
import UpperNavbar from "@/components/layout/UpperNavbar/UpperNavbar";
import Footer from "@/components/layout/Footer/Footer";
import UpperFooter from "@/components/layout/UpperFooter/UpperFooter";

import Providers from "@/components/Providers/Providers";
import { ToastContainer } from "react-toastify";

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={exo.className}>
        <Providers>
          <UpperNavbar />
          <Navbar />
          <ToastContainer />
          <div className=" bg-gray-50/50">{children}</div>
          <UpperFooter />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
